dist: trusty
sudo: false
language: node_js
node_js:
  - "6.9.1"
cache:
  directories:
    - "node_modules"
addons:
  sonarcloud:
    organization: "nodechatapp"
    token:
      secure: "9d4f09661c7b04afc53658757603b5e8036ca712"

script:
  - "npm test"
  - "sonar-scanner"
