dist: trusty
sudo: false
language: node_js
node_js:
  - "6.9.1"
cache:
  directories:
    - "node_modules"
addons:
  sonarcloud:
    organization: "ksk-github"
    token:
      secure: "1a5e6fd9a26a119a696c0491207d72e66f7337c4"
script:
  - "npm test"
  # - "sonar-scanner"

deploy:
   provider: cloudfoundry
   username: santhoshkumarkcse@gmail.com
   password: Kansan\@123
   api: https://api.run.pivotal.io
   organization: santhoshkumark-org
   space: staging

travis encrypt --add deploy.password
