dist: trusty
sudo: false
language: node_js
node_js:
  - "6.9.1"
addons:
  sonarcloud:
    organization: "santhosh-ksk-github"
    token:
      secure: "2390cd4121464e84b393c793767a3c7c71c03f7c"
script:
  - "npm test"
  - "sonar-scanner"
