dist: trusty
sudo: false
language: node_js
node_js:
  - "6.9.1"
addons:
  sonarcloud:
    organization: "ksk-github"
    token:
      secure: "1a5e6fd9a26a119a696c0491207d72e66f7337c4"
script:
  - "npm test"
  - "sonar-scanner"
